# Generated by Django 3.1.7 on 2021-09-02 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig_id', models.CharField(max_length=30, unique=True)),
                ('num_serie', models.CharField(max_length=30, null=True)),
                ('detail', models.TextField()),
                ('buy_date', models.DateField(null=True)),
                ('guarantee_end_date', models.DateField(null=True)),
                ('mac_addr1', models.CharField(max_length=30)),
                ('mac_addr2', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_marque', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_modele', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeEquipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rpe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('equipement_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipement.equipement')),
                ('personnel_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personnel.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Ripe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_machine', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=30)),
                ('equipement_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='equipement.equipement')),
            ],
        ),
        migrations.CreateModel(
            name='EquipementNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(null=True)),
                ('equipement_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipement.equipement')),
                ('write_by_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='equipement',
            name='marque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipement.marque'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='modele',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipement.modele'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='seller_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='equipement.seller'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipement.typeequipement'),
        ),
    ]
