# Generated by Django 3.1.7 on 2021-09-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_societe', models.CharField(max_length=20)),
                ('siret', models.CharField(max_length=30)),
                ('ape', models.CharField(max_length=20)),
                ('nom_gerant', models.CharField(max_length=30)),
            ],
        ),
    ]
