# Generated by Django 3.1.7 on 2021-09-02 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('societe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocole', models.CharField(max_length=10)),
                ('srv_entrant', models.CharField(max_length=30)),
                ('login_srv_entrant', models.CharField(max_length=30)),
                ('pwd_srv_entrant', models.CharField(max_length=30)),
                ('port_srv_entrant', models.IntegerField()),
                ('srv_sortant', models.CharField(max_length=30)),
                ('login_srv_sortant', models.CharField(max_length=30)),
                ('pwd_srv_sortant', models.CharField(max_length=30)),
                ('ssl_or_other', models.CharField(max_length=10)),
                ('authentification', models.CharField(max_length=20)),
                ('port_srv_sortant', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HebergeurMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_hebergeur', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_mail', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=30)),
                ('alias', models.CharField(max_length=255)),
                ('etat', models.CharField(max_length=50)),
                ('nbr_utilisation', models.IntegerField(null=True)),
                ('capacite', models.IntegerField(null=True)),
                ('mo_go', models.CharField(max_length=3)),
                ('commentaire', models.TextField()),
                ('config_mail_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mail.configmail')),
            ],
        ),
        migrations.AddField(
            model_name='configmail',
            name='hebergeur_mail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mail.hebergeurmail'),
        ),
        migrations.AddField(
            model_name='configmail',
            name='nom_societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='societe.societe'),
        ),
    ]
